Vagrant.configure("2") do |config|
  config.vm.box = "bionic64"
  config.vm.box_check_update = false
  config.ssh.insert_key = false

  config.vm.define "vm1" do |vm1|
      vm1.vm.hostname = "vm1.test.local"
      vm1.vm.provider "virtualbox" do |vb|
         vb.check_guest_additions = false
         vb.memory = "4096"
         vb.cpus = "3"
      end
      vm1.vm.network "forwarded_port", guest: 80,host: 8080
      vm1.vm.network "forwarded_port", guest: 22,host: 2221, id: "ssh"
      vm1.vm.network "private_network", ip: "192.168.63.10"
  end

  config.vm.define "vm2" do |vm2|
      vm2.vm.hostname = "vm2.test.local"
      vm2.vm.provider "virtualbox" do |vb|
         vb.check_guest_additions = false
         vb.memory = "3072"
         vb.cpus = "2"
      end
      vm2.vm.network "forwarded_port", guest: 80,host: 8081
      vm2.vm.network "forwarded_port", guest: 22,host: 2222, id: "ssh"
      vm2.vm.network "private_network", ip: "192.168.63.11"
  end


  config.vm.define "vm3" do |vm3|
      vm3.vm.hostname = "vm3"
      vm3.vm.provider "virtualbox" do |vb|
         vb.check_guest_additions = false
         vb.memory = "2048"
         vb.cpus = "2"
      end
      vm3.vm.network "forwarded_port", guest: 22,host: 2223, id: "ssh"
      vm3.vm.network "forwarded_port", guest: 80,host: 8082
  end
end
