all:
  hosts:
    vm1:
      ansible_host: 127.0.0.1
      ansible_ssh_port: 2221
      ansible_private_key_file: /root/.vagrant.d/insecure_private_key
      ansible_user: vagrant
      ansible_become: true
      description: freeipa-server

    vm2:
      ansible_host: 127.0.0.1
      ansible_ssh_port: 2222
      ansible_private_key_file: /root/.vagrant.d/insecure_private_key
      ansible_user: vagrant
      ansible_become: true
      description: freeipa-client,foreman

    vm3:
      ansible_host: 127.0.0.1
      ansible_ssh_port: 2223
      ansible_private_key_file: /root/.vagrant.d/insecure_private_key
      ansible_user: vagrant
      ansible_become: true
      description: docker,zabbix
